/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2018-04-05 15:39:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;
import java.sql.Connection;
import jdbc.*;
import charactor.*;
import java.sql.*;

public final class student_005fallroot_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

stuDAO stud = new stuDAO();
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"shr\" align=\"center\" style=\"margin-top: 50\">\r\n");
      out.write("\t\t<div style=\"font-size: 24\">输入学生信息</div>\r\n");
      out.write("\t\t<form id=\"myform\"  method=\"post\">\r\n");
      out.write("\t\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 100px\">姓名：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"sname\" name=\"xming\" style=\"font-size: 24\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 100px\">年龄：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"sage\" name=\"nling\" style=\"font-size: 24\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 100\">性别：</td>\r\n");
      out.write("\t\t\t\t\t<td><input style=\"font-size: 24\" type=\"radio\" name=\"xbie\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"男\" checked />男 <input style=\"font-size: 24\" type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\tname=\"xbie\" value=\"女\" />女</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 100\">爱好：</td>\r\n");
      out.write("\t\t\t\t\t<td><input style=\"font-size: 24\" type=\"checkbox\" name=\"aih\" />体育\r\n");
      out.write("\t\t\t\t\t\t<input style=\"font-size: 24\" type=\"checkbox\" name=\"aih\" />音乐 <input\r\n");
      out.write("\t\t\t\t\t\tstyle=\"font-size: 24\" type=\"checkbox\" name=\"aih\" />旅游 <input\r\n");
      out.write("\t\t\t\t\t\tstyle=\"font-size: 24\" type=\"checkbox\" name=\"aih\" />游戏</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 100\">学院：</td>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"xyuan\" style=\"font-size: 24\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"--------\">--------</option>\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 100\">专业：</td>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"zhye\" style=\"font-size: 24\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"--------\">--------</option>\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<p />\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"button\" name=\"add\" id=\"add\" value=\"添加学生信息\" ></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"reset\" name=\"reset\" value=\"重置\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 100\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery-1.12.4.js\" ></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script >\r\n");
      out.write("$(function () {\r\n");
      out.write("\talert(\"sss\");\r\n");
      out.write("\t$(\"#add\").click(function (){\r\n");
      out.write("\talert(\"aaa\");\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t\r\n");
      out.write("\t\turl:\"add.jsp\",\r\n");
      out.write("\t    type:\"post\",\r\n");
      out.write("\t    dataType:\"html\",\r\n");
      out.write("\t    \r\n");
      out.write("\t    data:{\r\n");
      out.write("\t    \t\"sname\":$(\"#sname\").val(),\r\n");
      out.write("\t    \t\"sage\":$(\"#sage\").val,\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    },\r\n");
      out.write("\tsuccess:function(data){\r\n");
      out.write("\t\talert(\"bbb\");\r\n");
      out.write("\t\tsb.append(\"<tr><td>id</td><td>name</td><td>hp</td><td>damage</td></tr>\\r\\n\");\r\n");
      out.write("\t\t$(\"#llan\").append(\"<tr><td>data.sname</td><td>data.sage</td></tr>\");\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("} )})\r\n");
      out.write("</script>\r\n");
      out.write("\t<div id=\"llan\" align=\"center\">\r\n");
      out.write("\t\t<div style=\"font-size: 24\">学生信息浏览</div>\r\n");
      out.write("\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t<td style=\"width: 100\">姓名</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 100\">年龄</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 100\">性别</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 100\">爱好</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 100\">学院</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 100\">专业</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 100\">修改与删除</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t");

					int total = new stuDAO().getTotal();

					List<Student> students = new stuDAO().list(0, total);
					System.out.println(students);
					request.setAttribute("students", students);
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /student_allroot.jsp(111,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${students}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /student_allroot.jsp(111,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("student");
      // /student_allroot.jsp(111,4) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t<tr align=\"center\">\r\n");
            out.write("\t\t\t\t\t\t");

							System.out.println("hhh");
						
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<td style=\"width: 100\">");
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.sage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.ssex}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.shobby}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.sschool}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.smajor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<td><input type=\"button\" id=\"update\" name=\"update\"\r\n");
            out.write("\t\t\t\t\t\t\tonclick=\"updateById(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(")\" value=\"修改\"> <input\r\n");
            out.write("\t\t\t\t\t\t\ttype=\"button\" id=\"delete\" name=\"delete\"\r\n");
            out.write("\t\t\t\t\t\t\tonclick=\"deleteById(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(")\" value=\"删除\"></td>\r\n");
            out.write("\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      }
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" LANGUAGE=\"JavaScript\">\r\n");
      out.write("function deleteById(id) {\r\n");
      out.write("\tvar studentId=id;\r\n");
      out.write("\twindow.location.href=\"student_delete.jsp?id=\"+studentId; \r\n");
      out.write("\r\n");
      out.write("} \r\n");
      out.write("function updateById(id,ssex) {\r\n");
      out.write("//\tdocument.write(\"xiug\");\r\n");
      out.write("\tvar studentId=id;\r\n");
      out.write("//\tvar studentSsex=ssex;\r\n");
      out.write("\twindow.location.href=\"student_update.jsp?id=\"+studentId; \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /student_allroot.jsp(116,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.sname}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }
}
